In [62]:
import pandas as pd
import numpy as np
df = pd.read_csv('SampleSuperstore.csv')

In [63]:
df.head(5)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   str
 1   Segment       9994 non-null   str
 2   Country       9994 non-null   str
 3   City          9994 non-null   str
 4   State         9994 non-null   str
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   str
 7   Category      9994 non-null   str
 8   Sub-Category  9994 non-null   str
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), str(8)
memory usage: 1015.1 KB

In [65]:
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [66]:
df['Profit_Margin'] = df['Profit'] / df['Sales'].replace(0, np.nan)
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_Margin
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,0.1600
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,0.3000
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,0.4700
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-0.4000
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,0.1125

In [67]:
Cat_sub = df.groupby(['Category','Sub-Category']).agg(
    Total_Sales = ('Sales','sum'),
    Total_Profit = ('Profit','sum'),
    Avg_Discount = ('Discount','mean'),
    Avg_Margin = ('Profit_Margin','mean')
).sort_values('Total_Profit')
# df.groupby(['Category', 'Sub-Category']).agg({'Sales': 'sum', 'Profit':'sum', 'Discount': 'mean', 'Profit Margin': 'mean'}).sort_values(by='Profit')
Cat_sub

                              Total_Sales  Total_Profit  Avg_Discount  \
Category        Sub-Category
Furniture       Tables        206965.5320   -17725.4811      0.261285
                Bookcases     114879.9963    -3472.5560      0.211140
Office Supplies Supplies       46673.5380    -1189.0995      0.076842
                Fasteners       3024.2800      949.5182      0.082028
Technology      Machines      189238.6310     3384.7569      0.306087
Office Supplies Labels         12486.3120     5546.2540      0.068681
                Art            27118.7920     6527.7870      0.074874
                Envelopes      16476.4020     6964.1767      0.080315
Furniture       Furnishings    91705.1640    13059.1436      0.138349
Office Supplies Appliances    107532.1610    18138.0054      0.166524
                Storage       223843.6080    21278.8264      0.074704
Furniture       Chairs        328449.1030    26590.1663      0.170178
Office Supplies Binders       203412.7330    30221.7633      0.372292
                Paper          78479.2060    34053.5693      0.074891
Technology      Accessories   167380.3180    41936.6357      0.078452
                Phones        330007.0540    44515.7306      0.154556
                Copiers       149528.0300    55617.8249      0.161765

                              Avg_Margin
Category        Sub-Category
Furniture       Tables         -0.147727
                Bookcases      -0.126640
Office Supplies Supplies        0.112039
                Fasteners       0.299171
Technology      Machines       -0.072026
Office Supplies Labels          0.429663
                Art             0.251646
                Envelopes       0.423140
Furniture       Furnishings     0.137066
Office Supplies Appliances     -0.156869
                Storage         0.089113
Furniture       Chairs          0.043900
Office Supplies Binders        -0.199595
                Paper           0.425600
Technology      Accessories     0.218210
                Phones          0.119222
                Copiers         0.317194

In [68]:
sort = df.groupby(['Sub-Category']).sum(numeric_only = True).idxmin()['Profit']
sort
print(f'The Sub-Category that loses the most money is {sort}')

Table_loss_percent = Cat_sub.loc[('Furniture', 'Tables'), 'Avg_Discount']*100
Bookcases_loss_percent = Cat_sub.loc[('Furniture', 'Bookcases'), 'Avg_Discount']*100

furn_loss = Cat_sub.loc[('Furniture',['Tables','Bookcases']), 'Total_Profit'].sum()*(-1)

The Sub-Category that loses the most money is Tables

In [69]:
bins = [-0.001, 0, 0.2, 0.5, 1.0] 
labels = ['No Discount', 'Low', 'Medium', 'High']
df['Discount_Bin'] = pd.cut(df['Discount'], bins=bins, labels=labels, include_lowest=True)
#df['Discount_Bin'] = df['Discount'].apply(lambda x: 'No Discount' if x == 0 else 'Low' if x <= 0.2 else 'Medium' if x <= 0.5 else 'High Discount')
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit,Profit_Margin,Discount_Bin
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,0.1600,No Discount
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,0.3000,No Discount
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,0.4700,No Discount
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,-0.4000,Medium
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,0.1125,Low

In [70]:
# High_Discount_Profit = df.groupby('Discount_Bin').agg({"Quantity": "count", "Sales": "sum", 'Profit': "sum"}).min()['Profit']
Discounts = df.groupby('Discount_Bin').agg(
    Total_Sales = ('Sales','sum'),
    Total_Profit = ('Profit','sum'),
    Order_count = ('Quantity', 'count'),
    Avg_Profit_Margin = ('Profit_Margin', 'mean')
)

In [71]:
High_Discount_Profit = Discounts.loc['High', 'Total_Profit']*(-1)
print(f"High Discount has the highest amount of negative profits {High_Discount_Profit}" )

High Discount has the highest amount of negative profits 76559.0513

In [ ]:
df.groupby(['Region', 'Segment']).agg(Total_sales = ('Sales', 'sum'), Total_profit = ('Profit', 'sum'))

                     Total_sales  Total_profit
Region  Segment
Central Consumer     252031.4340     8564.0481
        Corporate    157995.8128    18703.9020
        Home Office   91212.6440    12438.4124
East    Consumer     350908.1670    41190.9843
        Corporate    200409.3470    23622.5789
        Home Office  127463.7260    26709.2168
South   Consumer     195580.9710    26913.5728
        Corporate    121885.9325    15215.2232
        Home Office   74255.0015     4620.6343
West    Consumer     362880.7730    57450.6040
        Corporate    225855.2745    34437.4299
        Home Office  136721.7770    16530.4150

In [73]:
most_profitable = df.groupby(['Region', 'Segment']).agg({'Sales': 'sum', "Profit": 'sum'}).idxmax()['Profit']
least_profitable = df.groupby(['Region', 'Segment']).agg({'Sales': 'sum', "Profit": 'sum'}).idxmin()['Profit']

print(f"The Region-Segment combination is most profitable in {most_profitable} and least profitable in {least_profitable}")

region_profit = df.groupby('Region')['Profit'].sum()
loss_regions = region_profit[region_profit < 0]
print('Regions with overall loss:', loss_regions.index.tolist())

The Region-Segment combination is most profitable in ('West', 'Consumer') and least profitable in ('South', 'Home Office')
Regions with overall loss: []

In [74]:

Neg_ation = df[df['Profit'] < 0]
Neg_ation.groupby(['Sub-Category','Region','Segment'])['Profit'].sum().sort_values().head(3)

Sub-Category  Region   Segment
Binders       Central  Consumer    -13407.1203
Machines      East     Consumer    -10243.9352
Binders       Central  Corporate    -6580.0649
Name: Profit, dtype: float64

In [75]:
Unprofitable_orders = Neg_ation[['Sub-Category', 'Region','Segment']].value_counts().idxmax()

print(f"The Sub-Category, Region, and Segment  that appear most frequently in unprofitable orders are {Unprofitable_orders} with a loss of $13,407")

The Sub-Category, Region, and Segment  that appear most frequently in unprofitable orders are ('Binders', 'Central', 'Consumer') with a loss of $13,407

In [76]:
Percentage = Neg_ation['Discount_Bin'].value_counts(normalize=True) * 100
Percentage

Discount_Bin
High           45.750935
Low            27.952966
Medium         26.296098
No Discount     0.000000
Name: proportion, dtype: float64

In [77]:
Percent = Percentage.loc[('High')] + Percentage.loc[('Medium')]

In [78]:
print(f"""The company is bleeding money primarily through aggressive discounting on a few problem products.

       Tables and Bookcases (Furniture) are sold at average discounts of {Table_loss_percent}% and {Bookcases_loss_percent}%, leading to combined losses of over ${furn_loss}K. 

       In Office Supplies, Binders are heavily discounted (avg 37%) and lose money, especially in the Central region among Consumer customers. 

       Meanwhile, high-discount (~{Percentage.loc[('High')]}%) sales – just 856 transactions – account for a staggering -${High_Discount_Profit}K in profit. 

       My recommendation: review discount policies for Tables and Binders immediately, and implement a discount cap or approval workflow for discounts above 40%.""")

The company is bleeding money primarily through aggressive discounting on a few problem products.

       Tables and Bookcases (Furniture) are sold at average discounts of 26.12852664576803% and 21.114035087719298%, leading to combined losses of over $21198.0371K.

       In Office Supplies, Binders are heavily discounted (avg 37%) and lose money, especially in the Central region among Consumer customers.

       Meanwhile, high-discount (~45.75093532870123%) sales – just 856 transactions – account for a staggering -$76559.0513K in profit.

       My recommendation: review discount policies for Tables and Binders immediately, and implement a discount cap or approval workflow for discounts above 40%.

In [79]:
print(Discounts[['Order_count']])

              Order_count
Discount_Bin
No Discount          4798
Low                  3803
Medium                537
High                  856